const gestionnaire = require("../models/gestionnaireModels");

const transactionsPrefaites = [
    {
      id_transac: 1,
      statut: 'vente',
      gestionnaire: 1,
      acheteur: 1,
      date_transaction: '2024-10-20',
      prix: 55.00,
      remise: 5.00,
      frais: 5.00,
      jeux: [
        {
          etiquette: 1,
          id_vendeur: 1,
          categorie: ['Jeu de société', 'Jeu familial'],
          intitule: 'Monopoly',
          editeur: 'Hasbro',
          prix: 25.00,
          date_depot: '2024-09-23',
        },
        {
          etiquette: 2,
          id_vendeur: 1,
          categorie: ['Jeu de stratégie', 'Jeu de société'],
          intitule: 'Catan',
          editeur: 'Kosmos',
          prix: 30.00,
          date_depot: '2024-09-23',
        },
      ],
    },
    {
      id_transac: 2,
      statut: 'depot',
      gestionnaire: 5,
      propriétaire: 2,
      date_transaction: '2024-09-23',
      prix: 85,
      remise: 5.00,
      frais: 5.00,
      jeux: [
        {
          etiquette: 3,
          id_vendeur: 3,
          categorie: ['Jeux vidéo', 'Jeu pour enfants'],
          intitule: 'The Legend of Zelda',
          editeur: 'Nintendo',
          prix: 60.00,
        },
        {
          etiquette: 4,
          id_vendeur: 3,
          categorie: ['Jeu de société', 'Jeu familial'],
          intitule: 'Cluedo',
          editeur: 'Hasbro',
          prix: 25.00,
        },
      ],
    },
    {
      id_transac: 3,
      statut: 'depot',
      gestionnaire: 3,
      propriétaire: 4,
      date_transaction: '2024-10-20',
      prix: 90,
      remise: 5.00,
      frais: 5.00,
      jeux: [
        {
          etiquette: 5,
          id_vendeur: 4,
          categorie: ['Jeu de stratégie', 'Jeu de société'],
          intitule: 'Risk',
          editeur: 'Hasbro',
          prix: 40.00,
        },
        {
          etiquette: 6,
          id_vendeur: 4,
          categorie: ['Jeu de cartes', 'Jeu de société'],
          intitule: 'Uno',
          editeur: 'Mattel',
          prix: 50.00,
        },
      ],
    },
  ];

  const vendeurPrefaits = [
    { id_vendeur: 1, nom: 'Dupont', prenom: 'Jean', email: 'jean.dupont@example.com', solde: 0.0 },
    { id_vendeur: 2, nom: 'Martin', prenom: 'Marie', email: 'marie.martin@example.com', solde: 0.0 },
    { id_vendeur: 3, nom: 'Bernard', prenom: 'Pierre', email: 'pierre.bernard@example.com', solde: 0.0 },
    { id_vendeur: 4, nom: 'Dubois', prenom: 'Lucie', email: 'lucie.dubois@example.com', solde: 0.0 },
    { id_vendeur: 5, nom: 'Thomas', prenom: 'Paul', email: 'paul.thomas@example.com', solde: 0.0 },
    { id_vendeur: 6, nom: 'Robert', prenom: 'Sophie', email: 'sophie.robert@example.com', solde: 0.0 },
    { id_vendeur: 7, nom: 'Richard', prenom: 'Julien', email: 'julien.richard@example.com', solde: 0.0 },
    { id_vendeur: 8, nom: 'Petit', prenom: 'Laura', email: 'laura.petit@example.com', solde: 0.0 },
    { id_vendeur: 9, nom: 'Durand', prenom: 'Antoine', email: 'antoine.durand@example.com', solde: 0.0 },
    { id_vendeur: 10, nom: 'Leroy', prenom: 'Claire', email: 'claire.leroy@example.com', solde: 0.0 }
  ];

const acheteurPrefaits = [
  { id_acheteur: 1, nom: 'Dupont', prenom: 'Jean', email: 'jean.dupont@example.com', adresse: '123 Rue de Paris' },
  { id_acheteur: 2, nom: 'Martin', prenom: 'Marie', email: 'marie.martin@example.com', adresse: '456 Avenue de Lyon' },
  { id_acheteur: 3, nom: 'Bernard', prenom: 'Pierre', email: 'pierre.bernard@example.com', adresse: '789 Boulevard de Marseille' },
  { id_acheteur: 4, nom: 'Dubois', prenom: 'Lucie', email: 'lucie.dubois@example.com', adresse: '101 Rue de Bordeaux' },
  { id_acheteur: 5, nom: 'Thomas', prenom: 'Paul', email: 'paul.thomas@example.com', adresse: '202 Avenue de Lille' },
  { id_acheteur: 6, nom: 'Robert', prenom: 'Sophie', email: 'sophie.robert@example.com', adresse: '303 Boulevard de Toulouse' },
  { id_acheteur: 7, nom: 'Richard', prenom: 'Julien', email: 'julien.richard@example.com', adresse: '404 Rue de Nice' },
  { id_acheteur: 8, nom: 'Petit', prenom: 'Laura', email: 'laura.petit@example.com', adresse: '505 Avenue de Nantes' },
  { id_acheteur: 9, nom: 'Durand', prenom: 'Antoine', email: 'antoine.durand@example.com', adresse: '606 Boulevard de Strasbourg' },
  { id_acheteur: 10, nom: 'Leroy', prenom: 'Claire', email: 'claire.leroy@example.com', adresse: '707 Rue de Rennes' }
];

const gestionnairePrefaits = [
  { id_gestionnaire: 1, nom: 'Dupont', prenom: 'Jean', email: 'jean.dupont@example.com' },
  { id_gestionnaire: 2, nom: 'Martin', prenom: 'Marie', email: 'marie.martin@example.com' },
  { id_gestionnaire: 3, nom: 'Bernard', prenom: 'Pierre', email: 'pierre.bernard@example.com' },
  { id_gestionnaire: 4, nom: 'Dubois', prenom: 'Lucie', email: 'lucie.dubois@example.com' },
  { id_gestionnaire: 5, nom: 'Thomas', prenom: 'Paul', email: 'paul.thomas@example.com' },
  { id_gestionnaire: 6, nom: 'Robert', prenom: 'Sophie', email: 'sophie.robert@example.com' },
  { id_gestionnaire: 7, nom: 'Richard', prenom: 'Julien', email: 'julien.richard@example.com' },
  { id_gestionnaire: 8, nom: 'Petit', prenom: 'Laura', email: 'laura.petit@example.com' },
  { id_gestionnaire: 9, nom: 'Durand', prenom: 'Antoine', email: 'antoine.durand@example.com' },
  { id_gestionnaire: 10, nom: 'Leroy', prenom: 'Claire', email: 'claire.leroy@example.com' }
];

const jeuxPrefaits = [
  {
    etiquette: 1,
    id_vendeur: 1,
    categorie: ['Jeu de société', 'Jeu familial'],
    intitule: 'Monopoly',
    editeur: 'Hasbro',
    date_depot: '2024-09-23',
    prix: 25.00,
  },
  {
    etiquette: 2,
    id_vendeur: 1,
    categorie: ['Jeu de stratégie', 'Jeu de société'],
    intitule: 'Catan',
    editeur: 'Kosmos',
    date_depot: '2024-09-23',
    prix: 30.00,
  },
  {
    etiquette: 3,
    id_vendeur: 3,
    categorie: ['Jeux vidéo', 'Jeu pour enfants'],
    intitule: 'The Legend of Zelda',
    editeur: 'Nintendo',
    date_depot: '2024-09-23',
    prix: 60.00,
  },
  {
    etiquette: 4,
    id_vendeur: 2,
    categorie: ['Jeu de société', 'Jeu familial'],
    intitule: 'Cluedo',
    editeur: 'Hasbro',
    date_depot: '2024-09-23',
    prix: 25.00,
  },
  {
    etiquette: 5,
    id_vendeur: 4,
    categorie: ['Jeu de stratégie', 'Jeu de société'],
    intitule: 'Risk',
    editeur: 'Hasbro',
    date_depot: '2024-09-23',
    prix: 40.00,
  },
  {
    etiquette: 6,
    id_vendeur: 5,
    categorie: ['Jeu de cartes', 'Jeu de société'],
    intitule: 'Uno',
    editeur: 'Mattel',
    date_depot: '2024-09-23',
    prix: 50.00,
  },
];

const categoriePrefaites = [
  { id_categorie: 1, nom: 'Action' },
  { id_categorie: 2, nom: 'Aventure' },
  { id_categorie: 3, nom: 'Simulation' },
  { id_categorie: 4, nom: 'Stratégie' },
  { id_categorie: 5, nom: 'RPG' },
  { id_categorie: 6, nom: 'Sport' },
  { id_categorie: 7, nom: 'Puzzle' },
  { id_categorie: 8, nom: 'Horreur' },
  { id_categorie: 9, nom: 'Plateforme' },
  { id_categorie: 10, nom: 'Course' },
  { id_categorie: 11, nom: 'FPS' },
  { id_categorie: 12, nom: 'TPS' },
  { id_categorie: 13, nom: 'MMO' },
  { id_categorie: 14, nom: 'Survie' },
  { id_categorie: 15, nom: 'Battle Royale' },
  { id_categorie: 16, nom: 'Rogue-like' },
  { id_categorie: 17, nom: 'Beat\'em all' },
  { id_categorie: 18, nom: 'Musical' },
  { id_categorie: 19, nom: 'Party Game' },
  { id_categorie: 20, nom: 'Visual Novel' },
  { id_categorie: 21, nom: 'Metroidvania' },
  { id_categorie: 22, nom: 'Hack\'n Slash' },
  { id_categorie: 23, nom: 'City Builder' },
  { id_categorie: 24, nom: 'Sandbox' },
  { id_categorie: 25, nom: 'Rythme' },
  { id_categorie: 26, nom: 'Tactical RPG' },
  { id_categorie: 27, nom: 'MMORPG' },
  { id_categorie: 28, nom: 'MOBA' },
  { id_categorie: 29, nom: 'Tower Defense' },
  { id_categorie: 30, nom: 'Visual Novel' },
  { id_categorie: 31, nom: 'Jeu de cartes' },
  { id_categorie: 32, nom: 'Jeu de société' },
  { id_categorie: 33, nom: 'Jeu de rôle' },
  { id_categorie: 34, nom: 'Jeu de stratégie' },
  { id_categorie: 35, nom: 'Jeu de tir' },
  { id_categorie: 36, nom: 'Jeux vidéo' },
];

    module.exports = {
        transactionsPrefaites,
        vendeurPrefaits,
        acheteurPrefaits,
        gestionnairePrefaits,
        jeuxPrefaits,
        categoriePrefaites,
    };